theme: jekyll-theme-minimal
title: PetcliniX - Proof your paradigm
description: Petclinix is a technology showcase project inspired by the classic Petclinic domain. It demonstrates a wide range of software paradigms, architectural styles, and design principles using a familiar veterinary clinic model.
